name: Deploy to GitHub Pages
on:
  push:
    branches:
      - rolling
      - humble

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Setup Graphviz
              uses: ts-graphviz/setup-graphviz@v2

            - name: Install dependencies with pip
              run: pip install --no-warn-script-location --user -r requirements.txt -c constraints.txt

            - name: Build the docs
              run: make multiversion

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4.0.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build/html
                  cname: ros2docs.robook.org
                  commit_message: ${{ github.event.head_commit.message }}
                  enable_jekyll: true
